# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket = "mybucket-2manage-terragrunt-backend"
    key    = "live/dev/vpc/terragrunt.tfstate"
    region = "ap-south-2"
  }
}
